#cloud-config
package_update: true
runcmd:
  - apt-get update
  - apt-get install -y software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt-get update
  - apt-get install -y python3.11 python3.11-venv python3.11-dev python3.11-distutils ffmpeg
  # python3 のデフォルトを 3.11 に切り替え
  - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
  - update-alternatives --set python3 /usr/bin/python3.11
  # pip3 も 3.11 に対応させる
  - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
  - ln -sf /usr/local/bin/pip3 /usr/bin/pip3
  # 必要パッケージを pip 経由でインストール
  - pip3 install --upgrade pip
  - pip3 install paramiko numpy scipy Pillow
